### ISSUE TITLE
Failed to instantiate component or class "servd\craftremoteassets\RevisionableResourceBehavior".

### ISSUE THREAD

**Issue by michalochman** [servdhost/craft-remote-assets#4]
Hello, I cannot use Admin panel after installing the plugin. I have tested on Craft 3.1.34.2 and 3.2.10.

```
Invalid Configuration – yii\base\InvalidConfigException
Failed to instantiate component or class "servd\craftremoteassets\RevisionableResourceBehavior".
↵ Caused by: ReflectionException
  Class servd\craftremoteassets\RevisionableResourceBehavior does not exist
  in /app/vendor/yiisoft/yii2/di/Container.php at line 431
```

```ReflectionException: Class servd\craftremoteassets\RevisionableResourceBehavior does not exist in /app/vendor/yiisoft/yii2/di/Container.php:431
Stack trace:
#0 /app/vendor/yiisoft/yii2/di/Container.php(431): ReflectionClass->__construct('servd\\craftremo...')
#1 /app/vendor/yiisoft/yii2/di/Container.php(365): yii\di\Container->getDependencies('servd\\craftremo...')
#2 /app/vendor/yiisoft/yii2/di/Container.php(156): yii\di\Container->build('servd\\craftremo...', Array, Array)
#3 /app/vendor/yiisoft/yii2/BaseYii.php(345): yii\di\Container->get('servd\\craftremo...', Array)
#4 /app/vendor/yiisoft/yii2/base/Component.php(750): yii\BaseYii::createObject('servd\\craftremo...')
#5 /app/vendor/yiisoft/yii2/base/Component.php(734): yii\base\Component->attachBehaviorInternal('RevisionableRes...', 'servd\\craftremo...')
#6 /app/vendor/yiisoft/yii2/base/Component.php(294): yii\base\Component->ensureBehaviors()
#7 /app/vendor/servd/craft-remote-assets/src/RemoteAssetManager.php(61): yii\base\Component->__call('getRevision', Array)
#8 /app/vendor/servd/craft-remote-assets/src/RemoteAssetManager.php(40): servd\craftremoteassets\RemoteAssetManager->currentRevision()
#9 /app/vendor/servd/craft-remote-assets/src/RemoteAssetManager.php(35): servd\craftremoteassets\RemoteAssetManager->fillExistingFiles()
#10 [internal function]: servd\craftremoteassets\RemoteAssetManager->__construct(Array)
#11 /app/vendor/yiisoft/yii2/di/Container.php(384): ReflectionClass->newInstanceArgs(Array)
#12 /app/vendor/yiisoft/yii2/di/Container.php(156): yii\di\Container->build('servd\\craftremo...', Array, Array)
#13 /app/vendor/yiisoft/yii2/BaseYii.php(349): yii\di\Container->get('servd\\craftremo...', Array, Array)
#14 /app/vendor/servd/craft-remote-assets/src/CraftRemoteAssets.php(56): yii\BaseYii::createObject(Array)
#15 [internal function]: servd\craftremoteassets\CraftRemoteAssets->servd\craftremoteassets\{closure}()
#16 /app/vendor/yiisoft/yii2/di/Container.php(508): call_user_func_array(Object(Closure), Array)
#17 /app/vendor/yiisoft/yii2/BaseYii.php(351): yii\di\Container->invoke(Object(Closure), Array)
#18 /app/vendor/yiisoft/yii2/di/ServiceLocator.php(137): yii\BaseYii::createObject(Object(Closure))
#19 /app/vendor/yiisoft/yii2/base/Module.php(742): yii\di\ServiceLocator->get('assetManager', true)
#20 /app/vendor/craftcms/cms/src/web/Application.php(348): yii\base\Module->get('assetManager', true)
#21 /app/vendor/yiisoft/yii2/base/Application.php(608): craft\web\Application->get('assetManager')
#22 /app/vendor/yiisoft/yii2/web/View.php(225): yii\base\Application->getAssetManager()
#23 /app/vendor/yiisoft/yii2/web/View.php(285): yii\web\View->getAssetManager()
#24 /app/vendor/marionnewlevant/snitch/src/Snitch.php(90): yii\web\View->registerAssetBundle('marionnewlevant...')
#25 /app/vendor/yiisoft/yii2/base/BaseObject.php(109): marionnewlevant\snitch\Snitch->init()
#26 /app/vendor/yiisoft/yii2/base/Module.php(158): yii\base\BaseObject->__construct(Array)
#27 /app/vendor/craftcms/cms/src/base/Plugin.php(127): yii\base\Module->__construct('snitch', Object(craft\web\Application), Array)
#28 [internal function]: craft\base\Plugin->__construct('snitch', Object(craft\web\Application), Array)
#29 /app/vendor/yiisoft/yii2/di/Container.php(384): ReflectionClass->newInstanceArgs(Array)
#30 /app/vendor/yiisoft/yii2/di/Container.php(156): yii\di\Container->build('marionnewlevant...', Array, Array)
#31 /app/vendor/yiisoft/yii2/BaseYii.php(349): yii\di\Container->get('marionnewlevant...', Array, Array)
#32 /app/vendor/craftcms/cms/src/services/Plugins.php(897): yii\BaseYii::createObject(Array, Array)
#33 /app/vendor/craftcms/cms/src/services/Plugins.php(230): craft\services\Plugins->createPlugin('snitch', Array)
#34 /app/vendor/craftcms/cms/src/base/ApplicationTrait.php(1285): craft\services\Plugins->loadPlugins()
#35 /app/vendor/craftcms/cms/src/web/Application.php(112): craft\web\Application->_postInit()
#36 /app/vendor/yiisoft/yii2/base/BaseObject.php(109): craft\web\Application->init()
#37 /app/vendor/yiisoft/yii2/base/Application.php(206): yii\base\BaseObject->__construct(Array)
#38 /app/vendor/craftcms/cms/src/web/Application.php(100): yii\base\Application->__construct(Array)
#39 [internal function]: craft\web\Application->__construct(Array)
#40 /app/vendor/yiisoft/yii2/di/Container.php(384): ReflectionClass->newInstanceArgs(Array)
#41 /app/vendor/yiisoft/yii2/di/Container.php(156): yii\di\Container->build('craft\\web\\Appli...', Array, Array)
#42 /app/vendor/yiisoft/yii2/BaseYii.php(349): yii\di\Container->get('craft\\web\\Appli...', Array, Array)
#43 /app/vendor/craftcms/cms/bootstrap/bootstrap.php(248): yii\BaseYii::createObject(Array)
#44 /app/vendor/craftcms/cms/bootstrap/web.php(52): require('/app/vendor/cra...')
#45 /app/public_html/index.php(20): require('/app/vendor/cra...')
#46 {main}

Next yii\base\InvalidConfigException: Failed to instantiate component or class "servd\craftremoteassets\RevisionableResourceBehavior". in /app/vendor/yiisoft/yii2/di/Container.php:433
Stack trace:
#0 /app/vendor/yiisoft/yii2/di/Container.php(365): yii\di\Container->getDependencies('servd\\craftremo...')
#1 /app/vendor/yiisoft/yii2/di/Container.php(156): yii\di\Container->build('servd\\craftremo...', Array, Array)
#2 /app/vendor/yiisoft/yii2/BaseYii.php(345): yii\di\Container->get('servd\\craftremo...', Array)
#3 /app/vendor/yiisoft/yii2/base/Component.php(750): yii\BaseYii::createObject('servd\\craftremo...')
#4 /app/vendor/yiisoft/yii2/base/Component.php(734): yii\base\Component->attachBehaviorInternal('RevisionableRes...', 'servd\\craftremo...')
#5 /app/vendor/yiisoft/yii2/base/Component.php(294): yii\base\Component->ensureBehaviors()
#6 /app/vendor/servd/craft-remote-assets/src/RemoteAssetManager.php(61): yii\base\Component->__call('getRevision', Array)
#7 /app/vendor/servd/craft-remote-assets/src/RemoteAssetManager.php(40): servd\craftremoteassets\RemoteAssetManager->currentRevision()
#8 /app/vendor/servd/craft-remote-assets/src/RemoteAssetManager.php(35): servd\craftremoteassets\RemoteAssetManager->fillExistingFiles()
#9 [internal function]: servd\craftremoteassets\RemoteAssetManager->__construct(Array)
#10 /app/vendor/yiisoft/yii2/di/Container.php(384): ReflectionClass->newInstanceArgs(Array)
#11 /app/vendor/yiisoft/yii2/di/Container.php(156): yii\di\Container->build('servd\\craftremo...', Array, Array)
#12 /app/vendor/yiisoft/yii2/BaseYii.php(349): yii\di\Container->get('servd\\craftremo...', Array, Array)
#13 /app/vendor/servd/craft-remote-assets/src/CraftRemoteAssets.php(56): yii\BaseYii::createObject(Array)
#14 [internal function]: servd\craftremoteassets\CraftRemoteAssets->servd\craftremoteassets\{closure}()
#15 /app/vendor/yiisoft/yii2/di/Container.php(508): call_user_func_array(Object(Closure), Array)
#16 /app/vendor/yiisoft/yii2/BaseYii.php(351): yii\di\Container->invoke(Object(Closure), Array)
#17 /app/vendor/yiisoft/yii2/di/ServiceLocator.php(137): yii\BaseYii::createObject(Object(Closure))
#18 /app/vendor/yiisoft/yii2/base/Module.php(742): yii\di\ServiceLocator->get('assetManager', true)
#19 /app/vendor/craftcms/cms/src/web/Application.php(348): yii\base\Module->get('assetManager', true)
#20 /app/vendor/yiisoft/yii2/base/Application.php(608): craft\web\Application->get('assetManager')
#21 /app/vendor/yiisoft/yii2/web/View.php(225): yii\base\Application->getAssetManager()
#22 /app/vendor/yiisoft/yii2/web/View.php(285): yii\web\View->getAssetManager()
#23 /app/vendor/marionnewlevant/snitch/src/Snitch.php(90): yii\web\View->registerAssetBundle('marionnewlevant...')
#24 /app/vendor/yiisoft/yii2/base/BaseObject.php(109): marionnewlevant\snitch\Snitch->init()
#25 /app/vendor/yiisoft/yii2/base/Module.php(158): yii\base\BaseObject->__construct(Array)
#26 /app/vendor/craftcms/cms/src/base/Plugin.php(127): yii\base\Module->__construct('snitch', Object(craft\web\Application), Array)
#27 [internal function]: craft\base\Plugin->__construct('snitch', Object(craft\web\Application), Array)
#28 /app/vendor/yiisoft/yii2/di/Container.php(384): ReflectionClass->newInstanceArgs(Array)
#29 /app/vendor/yiisoft/yii2/di/Container.php(156): yii\di\Container->build('marionnewlevant...', Array, Array)
#30 /app/vendor/yiisoft/yii2/BaseYii.php(349): yii\di\Container->get('marionnewlevant...', Array, Array)
#31 /app/vendor/craftcms/cms/src/services/Plugins.php(897): yii\BaseYii::createObject(Array, Array)
#32 /app/vendor/craftcms/cms/src/services/Plugins.php(230): craft\services\Plugins->createPlugin('snitch', Array)
#33 /app/vendor/craftcms/cms/src/base/ApplicationTrait.php(1285): craft\services\Plugins->loadPlugins()
#34 /app/vendor/craftcms/cms/src/web/Application.php(112): craft\web\Application->_postInit()
#35 /app/vendor/yiisoft/yii2/base/BaseObject.php(109): craft\web\Application->init()
#36 /app/vendor/yiisoft/yii2/base/Application.php(206): yii\base\BaseObject->__construct(Array)
#37 /app/vendor/craftcms/cms/src/web/Application.php(100): yii\base\Application->__construct(Array)
#38 [internal function]: craft\web\Application->__construct(Array)
#39 /app/vendor/yiisoft/yii2/di/Container.php(384): ReflectionClass->newInstanceArgs(Array)
#40 /app/vendor/yiisoft/yii2/di/Container.php(156): yii\di\Container->build('craft\\web\\Appli...', Array, Array)
#41 /app/vendor/yiisoft/yii2/BaseYii.php(349): yii\di\Container->get('craft\\web\\Appli...', Array, Array)
#42 /app/vendor/craftcms/cms/bootstrap/bootstrap.php(248): yii\BaseYii::createObject(Array)
#43 /app/vendor/craftcms/cms/bootstrap/web.php(52): require('/app/vendor/cra...')
#44 /app/public_html/index.php(20): require('/app/vendor/cra...')
#45 {main}```

**Comment by michalochman** [comment]
Removed Snitch just in case, stack trace is cleaner now:
```
ReflectionException: Class servd\craftremoteassets\RevisionableResourceBehavior does not exist in /app/vendor/yiisoft/yii2/di/Container.php:431
Stack trace:
#0 /app/vendor/yiisoft/yii2/di/Container.php(431): ReflectionClass->__construct('servd\\craftremo...')
#1 /app/vendor/yiisoft/yii2/di/Container.php(365): yii\di\Container->getDependencies('servd\\craftremo...')
#2 /app/vendor/yiisoft/yii2/di/Container.php(156): yii\di\Container->build('servd\\craftremo...', Array, Array)
#3 /app/vendor/yiisoft/yii2/BaseYii.php(345): yii\di\Container->get('servd\\craftremo...', Array)
#4 /app/vendor/yiisoft/yii2/base/Component.php(750): yii\BaseYii::createObject('servd\\craftremo...')
#5 /app/vendor/yiisoft/yii2/base/Component.php(734): yii\base\Component->attachBehaviorInternal('RevisionableRes...', 'servd\\craftremo...')
#6 /app/vendor/yiisoft/yii2/base/Component.php(294): yii\base\Component->ensureBehaviors()
#7 /app/vendor/servd/craft-remote-assets/src/RemoteAssetManager.php(61): yii\base\Component->__call('getRevision', Array)
#8 /app/vendor/servd/craft-remote-assets/src/RemoteAssetManager.php(40): servd\craftremoteassets\RemoteAssetManager->currentRevision()
#9 /app/vendor/servd/craft-remote-assets/src/RemoteAssetManager.php(35): servd\craftremoteassets\RemoteAssetManager->fillExistingFiles()
#10 [internal function]: servd\craftremoteassets\RemoteAssetManager->__construct(Array)
#11 /app/vendor/yiisoft/yii2/di/Container.php(384): ReflectionClass->newInstanceArgs(Array)
#12 /app/vendor/yiisoft/yii2/di/Container.php(156): yii\di\Container->build('servd\\craftremo...', Array, Array)
#13 /app/vendor/yiisoft/yii2/BaseYii.php(349): yii\di\Container->get('servd\\craftremo...', Array, Array)
#14 /app/vendor/servd/craft-remote-assets/src/CraftRemoteAssets.php(56): yii\BaseYii::createObject(Array)
#15 [internal function]: servd\craftremoteassets\CraftRemoteAssets->servd\craftremoteassets\{closure}()
#16 /app/vendor/yiisoft/yii2/di/Container.php(508): call_user_func_array(Object(Closure), Array)
#17 /app/vendor/yiisoft/yii2/BaseYii.php(351): yii\di\Container->invoke(Object(Closure), Array)
#18 /app/vendor/yiisoft/yii2/di/ServiceLocator.php(137): yii\BaseYii::createObject(Object(Closure))
#19 /app/vendor/yiisoft/yii2/base/Module.php(742): yii\di\ServiceLocator->get('assetManager', true)
#20 /app/vendor/craftcms/cms/src/web/Application.php(348): yii\base\Module->get('assetManager', true)
#21 /app/vendor/yiisoft/yii2/base/Application.php(608): craft\web\Application->get('assetManager')
#22 /app/vendor/yiisoft/yii2/web/View.php(225): yii\base\Application->getAssetManager()
#23 /app/vendor/yiisoft/yii2/web/View.php(285): yii\web\View->getAssetManager()
#24 /app/vendor/craftcms/cms/src/widgets/RecentEntries.php(148): yii\web\View->registerAssetBundle('craft\\web\\asset...')
#25 /app/vendor/craftcms/cms/src/controllers/DashboardController.php(514): craft\widgets\RecentEntries->getBodyHtml()
#26 /app/vendor/craftcms/cms/src/controllers/DashboardController.php(99): craft\controllers\DashboardController->_getWidgetInfo(Object(craft\widgets\RecentEntries))
#27 [internal function]: craft\controllers\DashboardController->actionIndex()
#28 /app/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#29 /app/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#30 /app/vendor/craftcms/cms/src/web/Controller.php(110): yii\base\Controller->runAction('index', Array)
#31 /app/vendor/yiisoft/yii2/base/Module.php(528): craft\web\Controller->runAction('index', Array)
#32 /app/vendor/craftcms/cms/src/web/Application.php(297): yii\base\Module->runAction('dashboard/index', Array)
#33 /app/vendor/yiisoft/yii2/web/Application.php(103): craft\web\Application->runAction('dashboard/index', Array)
#34 /app/vendor/craftcms/cms/src/web/Application.php(286): yii\web\Application->handleRequest(Object(craft\web\Request))
#35 /app/vendor/yiisoft/yii2/base/Application.php(386): craft\web\Application->handleRequest(Object(craft\web\Request))
#36 /app/public_html/index.php(21): yii\base\Application->run()
#37 {main}

Next yii\base\InvalidConfigException: Failed to instantiate component or class "servd\craftremoteassets\RevisionableResourceBehavior". in /app/vendor/yiisoft/yii2/di/Container.php:433
Stack trace:
#0 /app/vendor/yiisoft/yii2/di/Container.php(365): yii\di\Container->getDependencies('servd\\craftremo...')
#1 /app/vendor/yiisoft/yii2/di/Container.php(156): yii\di\Container->build('servd\\craftremo...', Array, Array)
#2 /app/vendor/yiisoft/yii2/BaseYii.php(345): yii\di\Container->get('servd\\craftremo...', Array)
#3 /app/vendor/yiisoft/yii2/base/Component.php(750): yii\BaseYii::createObject('servd\\craftremo...')
#4 /app/vendor/yiisoft/yii2/base/Component.php(734): yii\base\Component->attachBehaviorInternal('RevisionableRes...', 'servd\\craftremo...')
#5 /app/vendor/yiisoft/yii2/base/Component.php(294): yii\base\Component->ensureBehaviors()
#6 /app/vendor/servd/craft-remote-assets/src/RemoteAssetManager.php(61): yii\base\Component->__call('getRevision', Array)
#7 /app/vendor/servd/craft-remote-assets/src/RemoteAssetManager.php(40): servd\craftremoteassets\RemoteAssetManager->currentRevision()
#8 /app/vendor/servd/craft-remote-assets/src/RemoteAssetManager.php(35): servd\craftremoteassets\RemoteAssetManager->fillExistingFiles()
#9 [internal function]: servd\craftremoteassets\RemoteAssetManager->__construct(Array)
#10 /app/vendor/yiisoft/yii2/di/Container.php(384): ReflectionClass->newInstanceArgs(Array)
#11 /app/vendor/yiisoft/yii2/di/Container.php(156): yii\di\Container->build('servd\\craftremo...', Array, Array)
#12 /app/vendor/yiisoft/yii2/BaseYii.php(349): yii\di\Container->get('servd\\craftremo...', Array, Array)
#13 /app/vendor/servd/craft-remote-assets/src/CraftRemoteAssets.php(56): yii\BaseYii::createObject(Array)
#14 [internal function]: servd\craftremoteassets\CraftRemoteAssets->servd\craftremoteassets\{closure}()
#15 /app/vendor/yiisoft/yii2/di/Container.php(508): call_user_func_array(Object(Closure), Array)
#16 /app/vendor/yiisoft/yii2/BaseYii.php(351): yii\di\Container->invoke(Object(Closure), Array)
#17 /app/vendor/yiisoft/yii2/di/ServiceLocator.php(137): yii\BaseYii::createObject(Object(Closure))
#18 /app/vendor/yiisoft/yii2/base/Module.php(742): yii\di\ServiceLocator->get('assetManager', true)
#19 /app/vendor/craftcms/cms/src/web/Application.php(348): yii\base\Module->get('assetManager', true)
#20 /app/vendor/yiisoft/yii2/base/Application.php(608): craft\web\Application->get('assetManager')
#21 /app/vendor/yiisoft/yii2/web/View.php(225): yii\base\Application->getAssetManager()
#22 /app/vendor/yiisoft/yii2/web/View.php(285): yii\web\View->getAssetManager()
#23 /app/vendor/craftcms/cms/src/widgets/RecentEntries.php(148): yii\web\View->registerAssetBundle('craft\\web\\asset...')
#24 /app/vendor/craftcms/cms/src/controllers/DashboardController.php(514): craft\widgets\RecentEntries->getBodyHtml()
#25 /app/vendor/craftcms/cms/src/controllers/DashboardController.php(99): craft\controllers\DashboardController->_getWidgetInfo(Object(craft\widgets\RecentEntries))
#26 [internal function]: craft\controllers\DashboardController->actionIndex()
#27 /app/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#28 /app/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#29 /app/vendor/craftcms/cms/src/web/Controller.php(110): yii\base\Controller->runAction('index', Array)
#30 /app/vendor/yiisoft/yii2/base/Module.php(528): craft\web\Controller->runAction('index', Array)
#31 /app/vendor/craftcms/cms/src/web/Application.php(297): yii\base\Module->runAction('dashboard/index', Array)
#32 /app/vendor/yiisoft/yii2/web/Application.php(103): craft\web\Application->runAction('dashboard/index', Array)
#33 /app/vendor/craftcms/cms/src/web/Application.php(286): yii\web\Application->handleRequest(Object(craft\web\Request))
#34 /app/vendor/yiisoft/yii2/base/Application.php(386): craft\web\Application->handleRequest(Object(craft\web\Request))
#35 /app/public_html/index.php(21): yii\base\Application->run()
#36 {main}
```
